name: Inarifarms
description: $description
version: '${version}'
loader: dev.notmarra.inarifarms.loader.InariPluginLoader

main: dev.notmarra.inarifarms.Inarifarms
api-version: '26.2'
load: POSTWORLD

authors: [ NotMarra ]
website: notmarra.dev
